### ISSUE TITLE
Setup api-test project

### ISSUE THREAD

**Issue by emjunior258** [emjunior258/certeasy#18]
Create the project for API tests.

## Acceptance Criteria

- Project must be setup under `certeasy-api-test`
- All the boilerplate must be in place and must have at least one dummy test
- Project must be integrated into Github actions workflow `.github/workflows/certeasy.yaml`
- Tests must be executed after each docker build

**Comment by sambodirce** [comment]
@emjunior258 can you validate test project? (https://github.com/emjunior258/certeasy/actions/runs/5180279701)

let me know if you prefer to run the integration test on the backend job
example: 
`certeasy-backend:
    runs-on: ubuntu-latest
     # Existing steps for certeasy-backend job
      - name: Run tests
        run: |
          docker run --rm -v "$(pwd)/cert/src/tests:/application/tests" -w /application/tests certeasy-backend pytest`
