### ISSUE TITLE
Setup backend unit testing

### ISSUE THREAD

**Issue by emjunior258** [emjunior258/certeasy#41]
Setup unit testing on backend project:

- Unit tests being executed on all pipelines
- Code coverage being measured
- Test report XML being produced
- Test report being fed to Sonarqube
- Test report being processed by the [Test reporter action](https://github.com/marketplace/actions/test-reporter)

**Comment by snhane** [comment]
@emjunior258 
by backend, meaning  core, bouncy and b-app, right?
